language: ruby

script: bundle exec rake travis

matrix:
  include:
    - rvm: 1.9.3
      gemfile: Gemfile
notifications:
  email: manisha@shippable.com
 
before_install:
  - gem update --system #  todo: workaround for https://github.com/rubygems/rubygems/pull/763
